                export STORAGE_DEVICE="sdc"
                export STORAGE_DEVICE_PATH="/dev/sdc"
                export STORAGE_DEVICE_MODEL="WDC WD20EZRZ-00Z"
                export STORAGE_DEVICE_ID_BUS="ata"
                export STORAGE_DEVICE_BUS="sata"
                export STORAGE_DEVICE_TYPE="hdd"
                export STORAGE_DEVICE_ROTATIONAL="1"

                export STORAGE_PARTITION="sdc1"
                export STORAGE_PARTITION_PATH="/dev/sdc1"
                export STORAGE_PARTITION_PARENT_DEVICE="sdc"
                export STORAGE_PARTITION_FILESYSTEM=""
                export STORAGE_PARTITION_MOUNTPOINT=""
                export STORAGE_PARTITION_SIZE=" 16M"
                export STORAGE_PARTITION_UUID=""
                export STORAGE_PARTITION_PARTUUID="1e0847c5-c623-484f-b4d3-a6a1a88faefc"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS=""
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
