                export STORAGE_DEVICE="sdd"
                export STORAGE_DEVICE_PATH="/dev/sdd"
                export STORAGE_DEVICE_MODEL="Expansion Desk  "
                export STORAGE_DEVICE_ID_BUS="usb"
                export STORAGE_DEVICE_BUS="usb"
                export STORAGE_DEVICE_TYPE="usb"
                export STORAGE_DEVICE_ROTATIONAL="1"

                export STORAGE_PARTITION="sdd2"
                export STORAGE_PARTITION_PATH="/dev/sdd2"
                export STORAGE_PARTITION_PARENT_DEVICE="sdd"
                export STORAGE_PARTITION_FILESYSTEM="ntfs"
                export STORAGE_PARTITION_MOUNTPOINT="/media/protoman120/Seagate Expansion Drive"
                export STORAGE_PARTITION_SIZE=" 5,5T"
                export STORAGE_PARTITION_UUID="865A34E95A34D81F"
                export STORAGE_PARTITION_PARTUUID="0ce5cab2-6735-480b-b40a-4eed3e154b60"
                export STORAGE_PARTITION_LABEL="Seagate Expansion Drive"

                export STORAGE_PARTITION_MOUNT_OPTIONS="rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096"
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
