        export STORAGE_DEVICE="nvme0n1"
        export STORAGE_DEVICE_PATH="/dev/nvme0n1"
        export STORAGE_DEVICE_MODEL="KINGSTON SFYRS500G                      "
        export STORAGE_DEVICE_ID_BUS=""
        export STORAGE_DEVICE_BUS="nvme"
        export STORAGE_DEVICE_TYPE="nvme"
        export STORAGE_DEVICE_ROTATIONAL="0"

        export STORAGE_DEVICE_SCHEDULER="kyber"
        export STORAGE_DEVICE_DISCARD_MAX_BYTES="2199023255040"
        export STORAGE_DEVICE_READ_AHEAD_KB="32"
        export STORAGE_DEVICE_QUEUE_DEPTH=""
        export STORAGE_DEVICE_IO_STATS="0"
        export STORAGE_DEVICE_NOMERGES="2"
        export STORAGE_DEVICE_FRONT_MERGES=""
        export STORAGE_DEVICE_RQ_AFFINITY="2"
        export STORAGE_DEVICE_ASYNC_DEPTH=""
        export STORAGE_DEVICE_FIFO_BATCH=""
        export STORAGE_DEVICE_READ_EXPIRE=""
        export STORAGE_DEVICE_WRITES_STARVED=""
        export STORAGE_DEVICE_NR_REQUESTS="4"
        export STORAGE_DEVICE_IO_POLL="0"
        export STORAGE_DEVICE_IO_POLL_DELAY="-1"

