        #SYSTEM USER

        SYSTEM_USER=protoman120
        SYSTEM_SETUP_USER=protoman120

        SYSTEM_AUTOMATIC_UPDATES=false
        SYSTEM_PORTABLE_INSTALL=false

        #SCANNED HARDWARE (TO USE AS REFERENCE FOR PORTABLE INSTALLS)
        
        STORAGE_ROOT_DEVICE_TYPE=ssd
        SCANNED_CPU_CLASSIFICATION=''
        SCANNED_RAM_CLASSIFICATION=''
        
        #SELECTED PROFILE:

        OPTIMIZATION_PROFILE=gaming
        OPTIMIZATION_PROFILE_USECASE=gaming 

        #HARDWARE OPTIMIZATIONS:
	
        #CPU OPTIMIZATIONS:
        OPTIMIZATION_CPU_ENABLED=enabled      
        CPU_OPTIMIZATION_GOAL=latency
        CPU_COOLING_OPTIMIZATION=enabled

        #GPU OPTIMIZATIONS:
        OPTIMIZATION_GPU_ENABLED=enabled
        GPU_OPTIMIZATION_GOAL=latency
        GPU_COOLING_OPTIMIZATION=enabled

        #RAM OPTIMIZATIONS:
        OPTIMIZATION_RAM_ENABLED=enabled
        RAM_OPTIMIZATION_GOAL=latency

        #NETWORK OPTIMIZATIONS:
        OPTIMIZATION_NETWORK_ENABLED=enabled
        NETWORK_OPTIMIZATION_GOAL=latency

        #STORAGE_OPTIMIZATIONS:
        OPTIMIZATION_STORAGE_ENABLED=enabled
        HDD_STORAGE_OPTIMIZATION_GOAL=throughput
        SSD_STORAGE_OPTIMIZATION_GOAL=latency
        USB_STORAGE_OPTIMIZATION_GOAL=throughput
        NVME_STORAGE_OPTIMIZATION_GOAL=latency

        #SOFTWARE OPTIMIZATIONS:
        OPTIMIZATION_OS_ENABLED=enabled
        OPTIMIZATION_TMPFS_CACHING_ENABLED=enabled
        TMPFS_SYSTEM_CACHING=enabled
        TMPFS_GAMING_CACHING=''
        OPTIMIZATION_DE_ENABLED=enabled
        OPTIMIZATION_BOOTLOADER_ENABLED=enabled
