        export STORAGE_DEVICE="sdd"
        export STORAGE_DEVICE_PATH="/dev/sdd"
        export STORAGE_DEVICE_MODEL="Expansion Desk  "
        export STORAGE_DEVICE_ID_BUS="usb"
        export STORAGE_DEVICE_BUS="usb"
        export STORAGE_DEVICE_TYPE="usb"
        export STORAGE_DEVICE_ROTATIONAL="1"

        export STORAGE_DEVICE_SCHEDULER="mq-deadline"
        export STORAGE_DEVICE_DISCARD_MAX_BYTES="0"
        export STORAGE_DEVICE_READ_AHEAD_KB="0"
        export STORAGE_DEVICE_QUEUE_DEPTH="30"
        export STORAGE_DEVICE_IO_STATS="0"
        export STORAGE_DEVICE_NOMERGES="0"
        export STORAGE_DEVICE_FRONT_MERGES=""
        export STORAGE_DEVICE_RQ_AFFINITY="0"
        export STORAGE_DEVICE_ASYNC_DEPTH=""
        export STORAGE_DEVICE_FIFO_BATCH="1"
        export STORAGE_DEVICE_READ_EXPIRE="64"
        export STORAGE_DEVICE_WRITES_STARVED="1"
        export STORAGE_DEVICE_NR_REQUESTS="512"
        export STORAGE_DEVICE_IO_POLL="0"
        export STORAGE_DEVICE_IO_POLL_DELAY="-1"

