        export STORAGE_DEVICE="sdc"
        export STORAGE_DEVICE_PATH="/dev/sdc"
        export STORAGE_DEVICE_MODEL="WDC WD20EZRZ-00Z"
        export STORAGE_DEVICE_ID_BUS="ata"
        export STORAGE_DEVICE_BUS="sata"
        export STORAGE_DEVICE_TYPE="hdd"
        export STORAGE_DEVICE_ROTATIONAL="1"

        export STORAGE_DEVICE_SCHEDULER="bfq"
        export STORAGE_DEVICE_DISCARD_MAX_BYTES="0"
        export STORAGE_DEVICE_READ_AHEAD_KB="0"
        export STORAGE_DEVICE_QUEUE_DEPTH="32"
        export STORAGE_DEVICE_IO_STATS="0"
        export STORAGE_DEVICE_NOMERGES="0"
        export STORAGE_DEVICE_FRONT_MERGES=""
        export STORAGE_DEVICE_RQ_AFFINITY="0"
        export STORAGE_DEVICE_ASYNC_DEPTH=""
        export STORAGE_DEVICE_FIFO_BATCH=""
        export STORAGE_DEVICE_READ_EXPIRE=""
        export STORAGE_DEVICE_WRITES_STARVED=""
        export STORAGE_DEVICE_NR_REQUESTS="512"
        export STORAGE_DEVICE_IO_POLL="0"
        export STORAGE_DEVICE_IO_POLL_DELAY="-1"

