        export STORAGE_DEVICE="zram0"
        export STORAGE_DEVICE_PATH="/dev/zram0"
        export STORAGE_DEVICE_MODEL=""
        export STORAGE_DEVICE_ID_BUS=""
        export STORAGE_DEVICE_BUS="usb"
        export STORAGE_DEVICE_TYPE="usb"
        export STORAGE_DEVICE_ROTATIONAL="0"

        export STORAGE_DEVICE_SCHEDULER=""
        export STORAGE_DEVICE_DISCARD_MAX_BYTES="2199023255040"
        export STORAGE_DEVICE_READ_AHEAD_KB="0"
        export STORAGE_DEVICE_QUEUE_DEPTH=""
        export STORAGE_DEVICE_IO_STATS="0"
        export STORAGE_DEVICE_NOMERGES="0"
        export STORAGE_DEVICE_FRONT_MERGES=""
        export STORAGE_DEVICE_RQ_AFFINITY=""
        export STORAGE_DEVICE_ASYNC_DEPTH=""
        export STORAGE_DEVICE_FIFO_BATCH=""
        export STORAGE_DEVICE_READ_EXPIRE=""
        export STORAGE_DEVICE_WRITES_STARVED=""
        export STORAGE_DEVICE_NR_REQUESTS=""
        export STORAGE_DEVICE_IO_POLL="0"
        export STORAGE_DEVICE_IO_POLL_DELAY="-1"

