        export GPU_DRM_CARD="card1"
        export GPU_DRM_PATH="/sys/class/drm/card1"
        export GPU_PCI_BDF="0000:06:00.0"
        export GPU_PCI_PATH="/sys/devices/pci0000:00/0000:00:03.1/0000:06:00.0"
        export GPU_VENDOR="nvidia"
        export GPU_TYPE="dgpu"
        export GPU_CLASS="nvidia"
        export GPU_DRIVER="nvidia"
        export GPU_BOOT_VGA="1"
        export GPU_PCIE_LINK_SPEED="16.0 GT/s PCIe"
        export GPU_PCE_LINK_WIDTH="16"
        export GPU_PCIE_MAX_SPEED="32.0 GT/s PCIe"
        export GPU_PCIE_MAX_WIDTH="16"
        export GPU_VRAM="12227"
        export GPU_POWER_DRAW="22.17"
        export GPU_POWER_LIMIT="175.00"
        export GPU_POWER_MIN_LIMIT="175.00"
        export GPU_POWER_MAX_LIMIT="250.00"
        export GPU_POWER_AVERAGE=""
        export GPU_POWER_AVERAGE_W=""
        export GPU_POWER_CAP=""
        export GPU_POWER_CAP_W=""

    #INTEL ONLY:
        export GPU_FREQ_MIN=""
        export GPU_FREQ_MAX=""
        export GPU_FREQ_CUR=""
        export GPU_BUSY_PERCENT=""
        
    #NVIDIA ONLY:
        export GPU_CORE_CLOCK="517"
        export GPU_MEMORY_CLOCK="7001"
        export GPU_SM_CLOCK="517"
        export GPU_MAX_GRAPHICS_CLOCK="3090"
        export GPU_MAX_MEMORY_CLOCK="14001"
