                export STORAGE_DEVICE="sda"
                export STORAGE_DEVICE_PATH="/dev/sda"
                export STORAGE_DEVICE_MODEL="KINGSTON SA400S3"
                export STORAGE_DEVICE_ID_BUS="ata"
                export STORAGE_DEVICE_BUS="sata"
                export STORAGE_DEVICE_TYPE="ssd"
                export STORAGE_DEVICE_ROTATIONAL="0"

                export STORAGE_PARTITION="sda1"
                export STORAGE_PARTITION_PATH="/dev/sda1"
                export STORAGE_PARTITION_PARENT_DEVICE="sda"
                export STORAGE_PARTITION_FILESYSTEM="vfat"
                export STORAGE_PARTITION_MOUNTPOINT=""
                export STORAGE_PARTITION_SIZE="  2G"
                export STORAGE_PARTITION_UUID="28BC-F6DE"
                export STORAGE_PARTITION_PARTUUID="aadfa41f-3d3f-4b9e-bce7-d72c84b958d1"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS=""
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
