        export STORAGE_DEVICE="sde"
        export STORAGE_DEVICE_PATH="/dev/sde"
        export STORAGE_DEVICE_MODEL="MassStorageClass"
        export STORAGE_DEVICE_ID_BUS="usb"
        export STORAGE_DEVICE_BUS="usb"
        export STORAGE_DEVICE_TYPE="usb"
        export STORAGE_DEVICE_ROTATIONAL="1"

        export STORAGE_DEVICE_SCHEDULER="mq-deadline"
        export STORAGE_DEVICE_DISCARD_MAX_BYTES="0"
        export STORAGE_DEVICE_READ_AHEAD_KB="2048"
        export STORAGE_DEVICE_QUEUE_DEPTH="1"
        export STORAGE_DEVICE_IO_STATS="1"
        export STORAGE_DEVICE_NOMERGES="0"
        export STORAGE_DEVICE_FRONT_MERGES=""
        export STORAGE_DEVICE_RQ_AFFINITY="1"
        export STORAGE_DEVICE_ASYNC_DEPTH=""
        export STORAGE_DEVICE_FIFO_BATCH="16"
        export STORAGE_DEVICE_READ_EXPIRE="500"
        export STORAGE_DEVICE_WRITES_STARVED="2"
        export STORAGE_DEVICE_NR_REQUESTS="2"
        export STORAGE_DEVICE_IO_POLL="0"
        export STORAGE_DEVICE_IO_POLL_DELAY="-1"

