                export STORAGE_DEVICE="nvme0n1"
                export STORAGE_DEVICE_PATH="/dev/nvme0n1"
                export STORAGE_DEVICE_MODEL="KINGSTON SFYRS500G                      "
                export STORAGE_DEVICE_ID_BUS=""
                export STORAGE_DEVICE_BUS="nvme"
                export STORAGE_DEVICE_TYPE="nvme"
                export STORAGE_DEVICE_ROTATIONAL="0"

                export STORAGE_PARTITION="nvme0n1p2"
                export STORAGE_PARTITION_PATH="/dev/nvme0n1p2"
                export STORAGE_PARTITION_PARENT_DEVICE="nvme0n1"
                export STORAGE_PARTITION_FILESYSTEM=""
                export STORAGE_PARTITION_MOUNTPOINT=""
                export STORAGE_PARTITION_SIZE=" 16M"
                export STORAGE_PARTITION_UUID=""
                export STORAGE_PARTITION_PARTUUID="f436e27c-e835-4b07-9b89-9481849c86d4"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS=""
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
