#!/bin/bash

OPTIMIZATION_PROFILE="AI_Self_Hosting"
OPTIMIZATION_PROFILE_USECASE="server"
#HARDWARE OPTIMIZATIONS:

#CPU OPTIMIZATIONS:
OPTIMIZATION_CPU_ENABLED="enabled"       
CPU_OPTIMIZATION_GOAL="throughput"
CPU_COOLING_OPTIMIZATION="enabled"

#GPU OPTIMIZATIONS:
OPTIMIZATION_GPU_ENABLED="enabled"
GPU_OPTIMIZATION_GOAL="throughput"
GPU_COOLING_OPTIMIZATION="enabled"

#RAM OPTIMIZATIONS:
OPTIMIZATION_RAM_ENABLED="enabled"
RAM_OPTIMIZATION_GOAL="throughput"

#NETWORK OPTIMIZATIONS:
OPTIMIZATION_NETWORK_ENABLED="enabled"
NETWORK_OPTIMIZATION_GOAL="latency"

#STORAGE_OPTIMIZATIONS:
OPTIMIZATION_STORAGE_ENABLED="enabled"
HDD_STORAGE_OPTIMIZATION_GOAL="throughput"
SSD_STORAGE_OPTIMIZATION_GOAL="throughput"
USB_STORAGE_OPTIMIZATION_GOAL="throughput"
NVME_STORAGE_OPTIMIZATION_GOAL="throughput"

#SOFTWARE OPTIMIZATIONS:
OPTIMIZATION_TMPFS_CACHING_ENABLED="disabled"
TMPFS_SYSTEM_CACHING="disabled"
OPTIMIZATION_DE_ENABLED="disabled"

#KERNEL OPTIMIZATIONS:
OPTIMIZATION_OS_ENABLED="enabled"
OPTIMIZATION_BOOTLOADER_ENABLED="enabled"