#!/bin/bash

#SAME AS "GAMING" PROFILE, BUT WITHOUT CPU/GPU COOLING OPTIMIZATIONS
#HARDWARE OPTIMIZATIONS:
OPTIMIZATION_PROFILE="gaming_high_performance"
OPTIMIZATION_PROFILE_USECASE="gaming"

#CPU OPTIMIZATIONS:
OPTIMIZATION_CPU_ENABLED="enabled"       
CPU_OPTIMIZATION_GOAL="latency"
CPU_COOLING_OPTIMIZATION="disabled"

#GPU OPTIMIZATIONS:
OPTIMIZATION_GPU_ENABLED="enabled"
GPU_OPTIMIZATION_GOAL="latency"
GPU_COOLING_OPTIMIZATION="disabled"

#RAM OPTIMIZATIONS:
OPTIMIZATION_RAM_ENABLED="enabled"
RAM_OPTIMIZATION_GOAL="latency"

#NETWORK OPTIMIZATIONS:
OPTIMIZATION_NETWORK_ENABLED="enabled"
NETWORK_OPTIMIZATION_GOAL="latency"

#STORAGE_OPTIMIZATIONS:
OPTIMIZATION_STORAGE_ENABLED="enabled"
if [[ $STORAGE_ROOT_DEVICE_TYPE == "hdd" ]]; then
    HDD_STORAGE_OPTIMIZATION_GOAL="latency"
else
    HDD_STORAGE_OPTIMIZATION_GOAL="throughput"
fi 
SSD_STORAGE_OPTIMIZATION_GOAL="latency"
if [[ $STORAGE_ROOT_DEVICE_TYPE == "usb" ]]; then
    USB_STORAGE_OPTIMIZATION_GOAL="latency"
else
    USB_STORAGE_OPTIMIZATION_GOAL="throughput"
fi 
NVME_STORAGE_OPTIMIZATION_GOAL="latency"

#SOFTWARE OPTIMIZATIONS:
OPTIMIZATION_TMPFS_CACHING_ENABLED="disabled"

if [[ $STORAGE_ROOT_DEVICE_TYPE == "usb" ]]; then
    TMPFS_GAMING_CACHING="enabled"
fi
OPTIMIZATION_DE_ENABLED="enabled"

#KERNEL OPTIMIZATIONS:
OPTIMIZATION_OS_ENABLED="enabled"
OPTIMIZATION_BOOTLOADER_ENABLED="enabled"
KERNEL_OPTIMIZATION_GOAL="enabled"
