#!/bin/bash

OPTIMIZATION_PROFILE="latency"
OPTIMIZATION_PROFILE_USECASE="server"
#HARDWARE OPTIMIZATIONS:

#CPU OPTIMIZATIONS:
OPTIMIZATION_CPU_ENABLED="enabled"       
CPU_OPTIMIZATION_GOAL="latency"
CPU_COOLING_OPTIMIZATION="enabled"

#GPU OPTIMIZATIONS:
OPTIMIZATION_GPU_ENABLED="enabled"
GPU_OPTIMIZATION_GOAL="latency"
GPU_COOLING_OPTIMIZATION="enabled"

#RAM OPTIMIZATIONS:
OPTIMIZATION_RAM_ENABLED="enabled"
RAM_OPTIMIZATION_GOAL="latency"

#NETWORK OPTIMIZATIONS:
OPTIMIZATION_NETWORK_ENABLED="enabled"
NETWORK_OPTIMIZATION_GOAL="latency"

#STORAGE_OPTIMIZATIONS:
OPTIMIZATION_STORAGE_ENABLED="enabled"
HDD_STORAGE_OPTIMIZATION_GOAL="latency"
SSD_STORAGE_OPTIMIZATION_GOAL="latency"
USB_STORAGE_OPTIMIZATION_GOAL="latency"
NVME_STORAGE_OPTIMIZATION_GOAL="latency"

#SOFTWARE OPTIMIZATIONS:
OPTIMIZATION_TMPFS_CACHING_ENABLED="enabled"
TMPFS_SYSTEM_CACHING="enabled"
OPTIMIZATION_DE_ENABLED="enabled"

#KERNEL OPTIMIZATIONS:
OPTIMIZATION_OS_ENABLED="enabled"
OPTIMIZATION_BOOTLOADER_ENABLED="enabled"
KERNEL_OPTIMIZATION_GOAL="enabled"
