                export STORAGE_DEVICE="nvme0n1"
                export STORAGE_DEVICE_PATH="/dev/nvme0n1"
                export STORAGE_DEVICE_MODEL="KINGSTON SFYRS500G                      "
                export STORAGE_DEVICE_ID_BUS=""
                export STORAGE_DEVICE_BUS="nvme"
                export STORAGE_DEVICE_TYPE="nvme"
                export STORAGE_DEVICE_ROTATIONAL="0"

                export STORAGE_PARTITION="nvme0n1p1"
                export STORAGE_PARTITION_PATH="/dev/nvme0n1p1"
                export STORAGE_PARTITION_PARENT_DEVICE="nvme0n1"
                export STORAGE_PARTITION_FILESYSTEM="vfat"
                export STORAGE_PARTITION_MOUNTPOINT="/boot/efi"
                export STORAGE_PARTITION_SIZE=" 100M"
                export STORAGE_PARTITION_UUID="088C-D4E1"
                export STORAGE_PARTITION_PARTUUID="7947249a-4795-49a8-8d03-b00daec63de1"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS="rw,nosuid,nodev,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro"
                export STORAGE_PARTITION_READ_ONLY="true"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="true"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
