                export STORAGE_DEVICE="sdd"
                export STORAGE_DEVICE_PATH="/dev/sdd"
                export STORAGE_DEVICE_MODEL="Expansion Desk  "
                export STORAGE_DEVICE_ID_BUS="usb"
                export STORAGE_DEVICE_BUS="usb"
                export STORAGE_DEVICE_TYPE="usb"
                export STORAGE_DEVICE_ROTATIONAL="1"

                export STORAGE_PARTITION="sdd1"
                export STORAGE_PARTITION_PATH="/dev/sdd1"
                export STORAGE_PARTITION_PARENT_DEVICE="sdd"
                export STORAGE_PARTITION_FILESYSTEM=""
                export STORAGE_PARTITION_MOUNTPOINT=""
                export STORAGE_PARTITION_SIZE=" 128M"
                export STORAGE_PARTITION_UUID=""
                export STORAGE_PARTITION_PARTUUID="2fdb7b77-9fb7-4adc-8576-4b30d606f971"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS=""
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
