                export STORAGE_DEVICE="sda"
                export STORAGE_DEVICE_PATH="/dev/sda"
                export STORAGE_DEVICE_MODEL="KINGSTON SA400S3"
                export STORAGE_DEVICE_ID_BUS="ata"
                export STORAGE_DEVICE_BUS="sata"
                export STORAGE_DEVICE_TYPE="ssd"
                export STORAGE_DEVICE_ROTATIONAL="0"

                export STORAGE_PARTITION="sda2"
                export STORAGE_PARTITION_PATH="/dev/sda2"
                export STORAGE_PARTITION_PARENT_DEVICE="sda"
                export STORAGE_PARTITION_FILESYSTEM="btrfs"
                export STORAGE_PARTITION_MOUNTPOINT="/home"
                export STORAGE_PARTITION_SIZE="445,2G"
                export STORAGE_PARTITION_UUID="edf6d4b9-2a67-4df5-808a-99ae0507d74f"
                export STORAGE_PARTITION_PARTUUID="6a672dc4-8216-4238-89e5-9ab05c3c2197"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS="rw,noatime,lazytime,compress=zstd:5,ssd,discard=async,space_cache=v2,autodefrag,commit=90,subvolid=256,subvol=/@
rw,noatime,lazytime,compress=zstd:5,ssd,discard=async,space_cache=v2,autodefrag,commit=90,subvolid=257,subvol=/@home"
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="true"
