#!/bin/bash

OPTIMIZATION_PROFILE="desktop"
OPTIMIZATION_PROFILE_USECASE="desktop"
#HARDWARE OPTIMIZATIONS:

#CPU OPTIMIZATIONS:
OPTIMIZATION_CPU_ENABLED="enabled"       
CPU_OPTIMIZATION_GOAL="latency"
CPU_COOLING_OPTIMIZATION="enabled"

#GPU OPTIMIZATIONS:
OPTIMIZATION_GPU_ENABLED="enabled"
GPU_OPTIMIZATION_GOAL="latency"
GPU_COOLING_OPTIMIZATION="enabled"

#RAM OPTIMIZATIONS:
OPTIMIZATION_RAM_ENABLED="enabled"
RAM_OPTIMIZATION_GOAL="latency"

#NETWORK OPTIMIZATIONS:
OPTIMIZATION_NETWORK_ENABLED="enabled"
NETWORK_OPTIMIZATION_GOAL="latency"

#STORAGE_OPTIMIZATIONS:
OPTIMIZATION_STORAGE_ENABLED="enabled"
if [[ $STORAGE_ROOT_DEVICE_TYPE == "hdd" ]]; then
    HDD_STORAGE_OPTIMIZATION_GOAL="latency"
else
    HDD_STORAGE_OPTIMIZATION_GOAL="throughput"
fi 
SSD_STORAGE_OPTIMIZATION_GOAL="latency"
if [[ $STORAGE_ROOT_DEVICE_TYPE == "usb" ]]; then
    USB_STORAGE_OPTIMIZATION_GOAL="latency"
else
    USB_STORAGE_OPTIMIZATION_GOAL="throughput"
fi
NVME_STORAGE_OPTIMIZATION_GOAL="latency"

#SOFTWARE OPTIMIZATIONS:
OPTIMIZATION_TMPFS_CACHING_ENABLED="enabled"
TMPFS_SYSTEM_CACHING="enabled"

if [[ $STORAGE_ROOT_DEVICE_TYPE == "usb" ]]; then
    echo ""
else
    echo ""
fi
OPTIMIZATION_DE_ENABLED="enabled"

#KERNEL OPTIMIZATIONS:
OPTIMIZATION_OS_ENABLED="enabled"
OPTIMIZATION_BOOTLOADER_ENABLED="enabled"
KERNEL_OPTIMIZATION_GOAL="enabled"
