                export STORAGE_DEVICE="nvme0n1"
                export STORAGE_DEVICE_PATH="/dev/nvme0n1"
                export STORAGE_DEVICE_MODEL="KINGSTON SFYRS500G                      "
                export STORAGE_DEVICE_ID_BUS=""
                export STORAGE_DEVICE_BUS="nvme"
                export STORAGE_DEVICE_TYPE="nvme"
                export STORAGE_DEVICE_ROTATIONAL="0"

                export STORAGE_PARTITION="nvme0n1p3"
                export STORAGE_PARTITION_PATH="/dev/nvme0n1p3"
                export STORAGE_PARTITION_PARENT_DEVICE="nvme0n1"
                export STORAGE_PARTITION_FILESYSTEM="ntfs"
                export STORAGE_PARTITION_MOUNTPOINT=""
                export STORAGE_PARTITION_SIZE="464,9G"
                export STORAGE_PARTITION_UUID="161A8E991A8E7611"
                export STORAGE_PARTITION_PARTUUID="4d01bce4-1bd6-46d0-b0d8-e5cd1048de80"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS=""
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
