        export STORAGE_DEVICE="sda"
        export STORAGE_DEVICE_PATH="/dev/sda"
        export STORAGE_DEVICE_MODEL="KINGSTON SA400S3"
        export STORAGE_DEVICE_ID_BUS="ata"
        export STORAGE_DEVICE_BUS="sata"
        export STORAGE_DEVICE_TYPE="ssd"
        export STORAGE_DEVICE_ROTATIONAL="0"

        export STORAGE_DEVICE_SCHEDULER="kyber"
        export STORAGE_DEVICE_DISCARD_MAX_BYTES="2147450880"
        export STORAGE_DEVICE_READ_AHEAD_KB="128"
        export STORAGE_DEVICE_QUEUE_DEPTH="32"
        export STORAGE_DEVICE_IO_STATS="0"
        export STORAGE_DEVICE_NOMERGES="1"
        export STORAGE_DEVICE_FRONT_MERGES=""
        export STORAGE_DEVICE_RQ_AFFINITY="1"
        export STORAGE_DEVICE_ASYNC_DEPTH=""
        export STORAGE_DEVICE_FIFO_BATCH=""
        export STORAGE_DEVICE_READ_EXPIRE=""
        export STORAGE_DEVICE_WRITES_STARVED=""
        export STORAGE_DEVICE_NR_REQUESTS="4"
        export STORAGE_DEVICE_IO_POLL="0"
        export STORAGE_DEVICE_IO_POLL_DELAY="-1"

