                export STORAGE_DEVICE="sdb"
                export STORAGE_DEVICE_PATH="/dev/sdb"
                export STORAGE_DEVICE_MODEL="CT1000BX500SSD1 "
                export STORAGE_DEVICE_ID_BUS="ata"
                export STORAGE_DEVICE_BUS="sata"
                export STORAGE_DEVICE_TYPE="ssd"
                export STORAGE_DEVICE_ROTATIONAL="0"

                export STORAGE_PARTITION="sdb1"
                export STORAGE_PARTITION_PATH="/dev/sdb1"
                export STORAGE_PARTITION_PARENT_DEVICE="sdb"
                export STORAGE_PARTITION_FILESYSTEM="btrfs"
                export STORAGE_PARTITION_MOUNTPOINT="/mnt/3d6f838e-7b11-420d-843e-ac6c7ff18c80"
                export STORAGE_PARTITION_SIZE="931,5G"
                export STORAGE_PARTITION_UUID="3d6f838e-7b11-420d-843e-ac6c7ff18c80"
                export STORAGE_PARTITION_PARTUUID="65823e8c-0a47-4efe-b600-3294f8dce719"
                export STORAGE_PARTITION_LABEL="Crucial_SSD"

                export STORAGE_PARTITION_MOUNT_OPTIONS="rw,nosuid,nodev,noatime,compress=zstd:5,ssd,discard=async,space_cache=v2,autodefrag,commit=120,subvolid=5,subvol=/"
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="true"
