                export STORAGE_DEVICE="sdc"
                export STORAGE_DEVICE_PATH="/dev/sdc"
                export STORAGE_DEVICE_MODEL="WDC WD20EZRZ-00Z"
                export STORAGE_DEVICE_ID_BUS="ata"
                export STORAGE_DEVICE_BUS="sata"
                export STORAGE_DEVICE_TYPE="hdd"
                export STORAGE_DEVICE_ROTATIONAL="1"

                export STORAGE_PARTITION="sdc2"
                export STORAGE_PARTITION_PATH="/dev/sdc2"
                export STORAGE_PARTITION_PARENT_DEVICE="sdc"
                export STORAGE_PARTITION_FILESYSTEM="ntfs"
                export STORAGE_PARTITION_MOUNTPOINT=""
                export STORAGE_PARTITION_SIZE=" 1,8T"
                export STORAGE_PARTITION_UUID="7EDA13C7DA137A9B"
                export STORAGE_PARTITION_PARTUUID="ad692c43-a26c-4c94-b1af-9633dfc81c4a"
                export STORAGE_PARTITION_LABEL="TORRE_HDD"

                export STORAGE_PARTITION_MOUNT_OPTIONS=""
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="false"
