                export STORAGE_DEVICE="sde"
                export STORAGE_DEVICE_PATH="/dev/sde"
                export STORAGE_DEVICE_MODEL="MassStorageClass"
                export STORAGE_DEVICE_ID_BUS="usb"
                export STORAGE_DEVICE_BUS="usb"
                export STORAGE_DEVICE_TYPE="usb"
                export STORAGE_DEVICE_ROTATIONAL="1"

                export STORAGE_PARTITION="sde1"
                export STORAGE_PARTITION_PATH="/dev/sde1"
                export STORAGE_PARTITION_PARENT_DEVICE="sde"
                export STORAGE_PARTITION_FILESYSTEM="btrfs"
                export STORAGE_PARTITION_MOUNTPOINT="/media/protoman120/a5968fab-f8ec-4617-8ad1-9736c4e9c5ca"
                export STORAGE_PARTITION_SIZE="119,1G"
                export STORAGE_PARTITION_UUID="a5968fab-f8ec-4617-8ad1-9736c4e9c5ca"
                export STORAGE_PARTITION_PARTUUID="461a47b7-121f-4bba-8b4e-afd0c8c566ed"
                export STORAGE_PARTITION_LABEL=""

                export STORAGE_PARTITION_MOUNT_OPTIONS="rw,nosuid,nodev,relatime,space_cache=v2,subvolid=5,subvol=/"
                export STORAGE_PARTITION_READ_ONLY="false"
                export STORAGE_PARTITION_SWAP="false"
                export STORAGE_PARTITION_EFI="false"
                export STORAGE_PARTITION_LUKS="false"
                export STORAGE_PARTITION_BTRFS="true"
